cuda: 1
seed: 123
epochs: 500
batch_size: 32
num_workers: 16
grad_acc_step: 1
grad_clip: 0.0
resume_checkpoint: /data/masters/projects/EDM-Dock/runs/run_0219/epoch=499-step=729999.ckpt
save_path: /data/masters/projects/EDM-Dock/runs
data:
  train_path: /data/masters/datasets/edm-dock-dataset-simple/train
  valid_path: /data/masters/datasets/edm-dock-dataset-simple/valid
  test_path: /data/masters/tools/EDM-Dock/examples
  filename: simple.pkl
model:
  optimizer:
    name: Adadelta
    lr: 0.001
  protein_net:
    model: egnn
    input_dim: 128
    hidden_dim: 256
    edge_dim: 0
    n_layers: 3
    activation: silu
  ligand_net:
    model: egnn
    input_dim: 144
    hidden_dim: 256
    edge_dim: 16
    n_layers: 3
    activation: silu
  interaction_net:
    model: mlp2
    input_dim: 512
    hidden_dim: 512
    n_layers: 3
    activation: relu
dock:
  k: 1.0
  n_sol: 1
  minimize: true

