cuda: 2
seed: 123
epochs: 500
batch_size: 32
num_workers: 8
grad_acc_step: 1
grad_clip: 0.0
resume_checkpoint: /data/masters/projects/EDM-Dock/runs/run_0234/epoch=499-step=729999.ckpt
save_path: /data/masters/projects/EDM-Dock/runs
data:
  train_path: /data/masters/datasets/edm-dock-dataset-simple/train
  valid_path: /data/masters/datasets/edm-dock-dataset-simple/valid
  test_path: /data/masters/datasets/edm-dock-dataset-simple/test
  filename: simple.pkl
model:
  optimizer:
    name: Adadelta
    lr: 0.01
  protein_net:
    model: egnn
    input_dim: 128
    hidden_dim: 256
    edge_dim: 0
    n_layers: 3
    activation: silu
  ligand_net:
    model: egnn
    input_dim: 144
    hidden_dim: 256
    edge_dim: 16
    n_layers: 3
    activation: silu
  interaction_net:
    model: l2
    input_dim: 512