cuda: 7
seed: 123
epochs: 100
batch_size: 1
num_workers: 8
grad_acc_step: 16
grad_clip: 0.0
resume_checkpoint: null
save_path: /data/masters/projects/EDM-Dock/runs
data:
  train_path: /data/masters/datasets/edm-dock-dataset/train
  valid_path: /data/masters/datasets/edm-dock-dataset/valid
  test_path: /data/masters/datasets/edm-dock-dataset/test/coreset
  filename: data.pkl
model:
  optimizer:
    name: Adadelta
    lr: 0.01
  protein_net:
    model: egnn
    input_dim: 23
    hidden_dim: 256
    n_layers: 3
    activation: silu
  ligand_net:
    model: egnn
    input_dim: 22
    hidden_dim: 256
    n_layers: 3
    activation: silu
  interaction_net:
    model: mlp
    input_dim: 512
    hidden_dim: 512
    n_layers: 3
    activation: relu