cuda: 5
seed: 123
epochs: 200
batch_size: 32
num_workers: 8
grad_acc_step: 1
grad_clip: 0.0
resume_checkpoint: null
save_path: /data/masters/projects/EDM-Dock/runs
data:
  train_path: /data/masters/datasets/edm-dock-dataset-esm/train+valid
  valid_path: /data/masters/datasets/edm-dock-dataset-esm/test
  test_path: /data/masters/datasets/edm-dock-dataset-esm/test
  filename: data_esm.pkl
model:
  optimizer:
    name: Adadelta
    lr: 0.1
  protein_net:
    model: egnn
    input_dim: 1303
    hidden_dim: 128
    n_layers: 3
    activation: relu
  ligand_net:
    model: egnn
    input_dim: 23
    hidden_dim: 128
    n_layers: 5
    activation: relu
  interaction_net:
    model: l2