cuda: 2
seed: 123
epochs: 100
batch_size: 1
num_workers: 4
grad_acc_step: 1
grad_clip: 0.0
resume_checkpoint: null
save_path: /data/masters/projects/EDM-Dock/runs
data:
  train_path: /data/masters/datasets/edm-dock-dataset-esm/train
  valid_path: /data/masters/datasets/edm-dock-dataset-esm/valid
  test_path: /data/masters/datasets/edm-dock-dataset-esm/test
  filename: data_esm.pkl
model:
  optimizer:
    name: Adadelta
    lr: 0.01
  protein_net:
    model: egnn
    input_dim: 1303
    hidden_dim: 64
    n_layers: 3
    activation: silu
  ligand_net:
    model: egnn
    input_dim: 23
    hidden_dim: 64
    n_layers: 5
    activation: silu
  interaction_net:
    model: attn
    input_dim: 64
    hidden_dim: 64
    n_layers: 3
    activation: silu