cuda: 6
seed: 123
epochs: 500
batch_size: 1
num_workers: 8
grad_acc_step: 1
grad_clip: 0.0
resume_checkpoint: null
save_path: /data/masters/projects/EDM-Dock/runs
data:
  train_path: /data/masters/datasets/edm-dock-dataset/test/coreset
  valid_path: /data/masters/datasets/edm-dock-dataset/test/coreset
  test_path: /data/masters/datasets/edm-dock-dataset/test/coreset
  filename: data_esm.pkl
model:
  optimizer:
    name: Adadelta
    lr: 0.001
  protein_net:
    model: egnn
    input_dim: 1303
    hidden_dim: 32
    n_layers: 3
    activation: silu
  ligand_net:
    model: egnn
    input_dim: 22
    hidden_dim: 32
    n_layers: 3
    activation: silu
  interaction_net:
    model: mlp
    input_dim: 32
    hidden_dim: 32
    n_layers: 3
    activation: relu