cuda: 6
seed: 123
epochs: 100
batch_size: 1
num_workers: 4
grad_acc_step: 16
resume_checkpoint: null
save_path: /data/masters/projects/EDM-Dock/runs
data:
  train_path: /data/masters/datasets/edm-dock-dataset/train
  valid_path: /data/masters/datasets/edm-dock-dataset/valid
  test_path: /data/masters/datasets/edm-dock-dataset/test/coreset
model:
  optimizer:
    name: Adadelta
    lr: 0.01
  protein_net:
    model: egnn
    input_dim: 1303
    hidden_dim: 256
    n_layers: 3
    activation: relu
  ligand_net:
    model: egnn
    input_dim: 22
    hidden_dim: 256
    n_layers: 3
    activation: relu
  interaction_net:
    model: l2